// A compact emoji list for the `:` picker: [emoji, space-separated search words].
// Deliberately small (the everyday set Notion's picker surfaces first) rather than the
// full Unicode table, which would add hundreds of KB to a 2 MB installer.
export const EMOJI = [
  ['😀', 'grinning smile happy'], ['😃', 'smiley happy'], ['😄', 'smile happy joy'], ['😁', 'grin beaming'],
  ['😆', 'laughing satisfied'], ['😅', 'sweat smile relief'], ['🤣', 'rofl rolling laughing'], ['😂', 'joy tears laughing'],
  ['🙂', 'slight smile'], ['🙃', 'upside down'], ['😉', 'wink'], ['😊', 'blush happy'],
  ['😇', 'innocent halo angel'], ['🥰', 'love hearts smiling'], ['😍', 'heart eyes love'], ['🤩', 'star struck excited'],
  ['😘', 'kiss blowing'], ['😋', 'yum delicious tongue'], ['😛', 'tongue'], ['😜', 'wink tongue crazy'],
  ['🤪', 'zany crazy'], ['🤔', 'thinking hmm'], ['🤨', 'raised eyebrow skeptical'], ['😐', 'neutral'],
  ['😑', 'expressionless'], ['😶', 'no mouth silent'], ['🙄', 'eye roll'], ['😏', 'smirk'],
  ['😬', 'grimace awkward'], ['😌', 'relieved calm'], ['😔', 'pensive sad'], ['😪', 'sleepy'],
  ['😴', 'sleeping zzz'], ['😷', 'mask sick'], ['🤒', 'thermometer ill'], ['🤯', 'mind blown exploding'],
  ['🥳', 'party celebrate'], ['😎', 'cool sunglasses'], ['🤓', 'nerd glasses'], ['🧐', 'monocle curious'],
  ['😕', 'confused'], ['😟', 'worried'], ['😮', 'open mouth surprised wow'], ['😲', 'astonished shocked'],
  ['😳', 'flushed embarrassed'], ['🥺', 'pleading puppy eyes'], ['😢', 'cry sad tear'], ['😭', 'sob crying'],
  ['😱', 'scream fear'], ['😤', 'triumph huff'], ['😡', 'rage angry mad'], ['🤬', 'cursing swearing'],
  ['💀', 'skull dead'], ['💩', 'poop'], ['🤡', 'clown'], ['👻', 'ghost'], ['👽', 'alien'], ['🤖', 'robot bot'],
  ['👋', 'wave hello bye hand'], ['👌', 'ok hand perfect'], ['✌️', 'victory peace'], ['🤞', 'crossed fingers luck'],
  ['👍', 'thumbs up yes like +1'], ['👎', 'thumbs down no dislike -1'], ['👏', 'clap applause'], ['🙌', 'raised hands hooray'],
  ['🙏', 'pray please thanks'], ['🤝', 'handshake deal'], ['💪', 'muscle strong flex'], ['👀', 'eyes look see'],
  ['🧠', 'brain think smart'], ['👶', 'baby'], ['🧑‍💻', 'technologist coder developer'], ['🎉', 'tada party celebration'],
  ['🎊', 'confetti'], ['🎁', 'gift present'], ['🎂', 'birthday cake'], ['🏆', 'trophy win'], ['🥇', 'gold medal first'],
  ['⭐', 'star'], ['🌟', 'glowing star'], ['✨', 'sparkles shiny new'], ['🔥', 'fire hot lit'], ['💯', '100 hundred perfect'],
  ['❤️', 'heart love red'], ['🧡', 'orange heart'], ['💛', 'yellow heart'], ['💚', 'green heart'], ['💙', 'blue heart'],
  ['💜', 'purple heart'], ['🖤', 'black heart'], ['🤍', 'white heart'], ['💔', 'broken heart'], ['💕', 'two hearts'],
  ['✅', 'check done yes white heavy'], ['☑️', 'ballot check box'], ['✔️', 'check mark'], ['❌', 'x cross no wrong'], ['❎', 'cross mark button'],
  ['⚠️', 'warning caution'], ['❗', 'exclamation important'], ['❓', 'question'], ['💡', 'bulb idea tip light'], ['📌', 'pushpin pin'],
  ['📍', 'round pushpin location'], ['🔖', 'bookmark'], ['🏷️', 'label tag'], ['🔗', 'link chain'], ['📎', 'paperclip attachment'],
  ['📝', 'memo note write'], ['📄', 'page document'], ['📃', 'page curl'], ['📑', 'bookmark tabs'], ['📚', 'books library read'],
  ['📖', 'open book read'], ['📓', 'notebook'], ['📒', 'ledger'], ['🗒️', 'spiral notepad'], ['🗓️', 'calendar spiral'],
  ['📅', 'date calendar'], ['⏰', 'alarm clock'], ['⏳', 'hourglass wait'], ['⌛', 'hourglass done time'], ['🕒', 'clock three time'],
  ['📊', 'bar chart stats'], ['📈', 'chart increasing up growth'], ['📉', 'chart decreasing down'], ['🗂️', 'card index dividers'], ['📁', 'folder file'],
  ['📂', 'open folder'], ['🗃️', 'card file box'], ['🗄️', 'file cabinet'], ['🗑️', 'wastebasket trash delete'], ['🔒', 'lock locked secure'],
  ['🔓', 'unlock open'], ['🔑', 'key password'], ['🔍', 'search magnifying zoom'], ['⚙️', 'gear settings'], ['🛠️', 'tools hammer wrench'],
  ['🔧', 'wrench fix'], ['🔨', 'hammer build'], ['🧪', 'test tube experiment'], ['🧩', 'puzzle piece'], ['🐛', 'bug'],
  ['🚀', 'rocket launch ship'], ['✈️', 'airplane travel flight'], ['🚗', 'car'], ['🚲', 'bicycle bike'], ['🏠', 'house home'],
  ['🏢', 'office building work'], ['🏫', 'school'], ['🌍', 'earth globe world'], ['🗺️', 'world map'], ['⛰️', 'mountain'],
  ['🏖️', 'beach vacation'], ['☀️', 'sun sunny'], ['🌙', 'moon night'], ['⛅', 'cloud sun'], ['🌧️', 'rain cloud'],
  ['❄️', 'snowflake cold'], ['🌈', 'rainbow'], ['⚡', 'zap lightning fast'], ['💧', 'droplet water'], ['🌊', 'wave ocean'],
  ['🌱', 'seedling plant grow'], ['🌳', 'tree'], ['🌸', 'cherry blossom flower'], ['🌻', 'sunflower'], ['🍀', 'four leaf clover luck'],
  ['🍎', 'apple red'], ['🍌', 'banana'], ['🍓', 'strawberry'], ['🍕', 'pizza'], ['🍔', 'hamburger burger'],
  ['🍜', 'ramen noodles'], ['🍣', 'sushi'], ['🍰', 'cake shortcake'], ['☕', 'coffee tea hot'], ['🍵', 'tea matcha'],
  ['🍺', 'beer'], ['🍷', 'wine'], ['🐶', 'dog puppy'], ['🐱', 'cat kitten'], ['🐼', 'panda'], ['🦊', 'fox'],
  ['🐻', 'bear'], ['🐸', 'frog'], ['🐧', 'penguin'], ['🦄', 'unicorn'], ['🐝', 'bee'], ['🦋', 'butterfly'],
  ['⚽', 'soccer football'], ['🏀', 'basketball'], ['🎮', 'video game controller'], ['🎲', 'die dice game'], ['🎯', 'dart target goal'],
  ['🎨', 'art palette paint'], ['🎵', 'music note'], ['🎧', 'headphones'], ['📷', 'camera photo'], ['🎬', 'clapper movie film'],
  ['💻', 'laptop computer'], ['🖥️', 'desktop computer'], ['⌨️', 'keyboard'], ['🖱️', 'mouse'], ['📱', 'phone mobile'],
  ['☎️', 'telephone'], ['📧', 'email mail'], ['✉️', 'envelope letter'], ['📦', 'package box'], ['💰', 'money bag'],
  ['💵', 'dollar money'], ['💳', 'credit card'], ['🛒', 'shopping cart'], ['🎓', 'graduation cap school'], ['✏️', 'pencil edit'],
  ['🖊️', 'pen'], ['📐', 'triangular ruler'], ['📏', 'straight ruler'], ['🧮', 'abacus'], ['🔔', 'bell notification'],
  ['🔕', 'bell off mute'], ['📣', 'megaphone announce'], ['💬', 'speech bubble comment chat'], ['💭', 'thought bubble'], ['🗨️', 'left speech bubble'],
  ['⬆️', 'up arrow'], ['⬇️', 'down arrow'], ['⬅️', 'left arrow'], ['➡️', 'right arrow'], ['🔄', 'repeat arrows refresh'],
  ['➕', 'plus add'], ['➖', 'minus'], ['✖️', 'multiply'], ['➗', 'divide'], ['♾️', 'infinity'],
  ['🟢', 'green circle'], ['🟡', 'yellow circle'], ['🔴', 'red circle'], ['🔵', 'blue circle'], ['⚪', 'white circle'],
  ['🇨🇳', 'china flag cn'], ['🇦🇺', 'australia flag au'], ['🇺🇸', 'usa flag us'], ['🇬🇧', 'uk flag gb'], ['🇯🇵', 'japan flag jp'],
];
